version: "3"
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - code_share:/var/www/public
  nginx:
    build:
      context: ./nginx
    volumes:
      - code_share:/var/www/public
    depends_on:
      - php-fpm

volumes:
  code_share:
    external: true