version: "3"
services:
  container1:
    build:
      context: ./container1
    volumes:
      - code_share:/var/www/public
  container2:
    build:
      context: ./container2
    volumes:
      - code_share:/var/www/public
    depends_on:
      - container1

volumes:
  code_share:
    external: true